# Generated by Django 4.0.6 on 2022-07-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('fd', 'Fine Dining'), ('cd', 'Casual Dining'), ('cc', 'Contemporary Casual'), ('fs', 'Family Style'), ('fc', 'Fast Casual'), ('ff', 'Fast Food'), ('c', 'Cafe'), ('b', 'Buffet'), ('ft', 'Food Truck')], max_length=6)),
                ('description', models.TextField()),
                ('website_url', models.CharField(blank=True, max_length=225, null=True)),
                ('contact_num', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('long', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
