# Generated by Django 4.0.6 on 2022-08-08 16:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0014_alter_event_creator_alter_review_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userextend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserExtend',
            new_name='User',
        ),
    ]
