# Generated by Django 4.0.6 on 2022-08-08 16:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userextend', '0002_rename_userextend_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserExtend',
        ),
    ]
