# Generated by Django 4.0.6 on 2022-08-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_event_photo_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='reviews',
            field=models.ManyToManyField(to='trip.review'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='reviews',
            field=models.ManyToManyField(to='trip.review'),
        ),
        migrations.AddField(
            model_name='thingtodo',
            name='reviews',
            field=models.ManyToManyField(to='trip.review'),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/events/'),
        ),
    ]
