# Generated by Django 4.0.6 on 2022-08-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0007_remove_review_event_event_reviews_restaurant_reviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='trip.review'),
        ),
    ]
