# Generated by Django 4.0.6 on 2022-08-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0008_alter_event_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/restaurants/'),
        ),
        migrations.AddField(
            model_name='thingtodo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/things_to_do/'),
        ),
    ]
