# Generated by Django 4.0.6 on 2022-08-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0009_restaurant_photo_thingtodo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(upload_to='static/images/events/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='photo',
            field=models.ImageField(upload_to='static/images/restaurants/'),
        ),
        migrations.AlterField(
            model_name='thingtodo',
            name='photo',
            field=models.ImageField(upload_to='static/images/things_to_do/'),
        ),
    ]
