# Generated by Django 4.0.6 on 2022-08-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0014_alter_event_creator_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='contact_num',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
