# Generated by Django 4.0.6 on 2022-09-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0015_alter_restaurant_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='avg_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
