# Generated by Django 4.0.6 on 2022-09-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0016_restaurant_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='avg_rating',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
