# Generated by Django 4.0.6 on 2022-09-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0017_event_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='thingtodo',
            name='avg_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='avg_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
