# Generated by Django 4.0.6 on 2022-10-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0019_alter_restaurant_lat_alter_restaurant_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, to='trip.review'),
        ),
    ]
