# Generated by Django 4.0.6 on 2022-10-28 16:40

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0025_alter_restaurant_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='reviews',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='events', to='trip.review'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='photo',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
