# Generated by Django 4.0.6 on 2022-10-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0026_alter_event_photo_alter_event_reviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(upload_to='static/images/events/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='photo',
            field=models.ImageField(upload_to='static/images/restaurants/'),
        ),
    ]
