# Generated by Django 4.0.6 on 2022-10-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0027_alter_event_photo_alter_restaurant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='events', to='trip.review'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='trip.review'),
        ),
    ]
