# Generated by Django 4.0.6 on 2022-10-28 17:17

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0028_alter_event_reviews_alter_restaurant_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thingtodo',
            name='reviews',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='trip.review'),
        ),
    ]
