# Generated by Django 4.0.6 on 2022-10-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0030_alter_thingtodo_lat_alter_thingtodo_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thingtodo',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='trip.review'),
        ),
    ]
